### ISSUE TITLE
Patch Submission

### ISSUE THREAD

**Issue by espositoandrea** [2qar/sent-pdf#2]
Hi!

I stumbled across this patch for sent and it's _fantastic_. So, I've tested it on the latest commit on the sent repository and, fantastic news, it works brilliantly. So I've decided to generate for you the patch file (that adheres to the suckless naming scheme). Either you submit it or not is up to you, but I think someone else would be happy to have a patch file to apply and that's why I'm sharing it :smile:.

Sadly, GitHub doesn't allow me to share it as a `.diff` file, so I'm uploading it with a `.txt` extension. Hope it helps! :smile: 

[sent-pdf-20201114-2649e8d.txt](https://github.com/BigHeadGeorge/sent-pdf/files/5540657/sent-pdf-20201114-2649e8d.txt)

**Comment by Davoodeh** [comment]
Bump!

This mastahpiece should be on the Suckless site. Seriously! Nobody knows about it.

P.S: Just applied the patch and a simple example (a pic and some text) works perfectly.

**Comment by 2qar** [comment]
Thank you @espositoandrea for the patch file submission, and thanks for the bump! I've submitted the patch to their site and added a release to this repository.
